site_name: Michale An Blog
site_author: Michael An
site_url: https://michael18811380328.github.io/
repo_name: Michael18811380328/Michael18811380328.github.io
repo_url: https://github.com/Michael18811380328/Michael18811380328.github.io
copyright: Copyright &copy; Michael An

docs_dir: ./docs

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - javascript
    palette:
        primary: "red"

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
#   - footnotes
#   - meta
#   - def_list
#   - pymdownx.arithmatex
#   - pymdownx.betterem:
#       smart_enable: all
#   - pymdownx.caret
#   - pymdownx.critic
#   - pymdownx.details
#   - pymdownx.emoji:
#       emoji_generator: !!python/name:pymdownx.emoji.to_png
#   - pymdownx.inlinehilite
#   - pymdownx.magiclink
#   - pymdownx.mark
#   - pymdownx.smartsymbols
#   - pymdownx.superfences
#   - pymdownx.tasklist
#   - pymdownx.tilde

# plugins:
#   - search # necessary for search to work

# extra:
#   search:
#     language: 'jp'

# Page tree
nav:
    - About:
        - '关于我': 'about/README.md'
        - '学习日志': 'about/log.md'
    - 算法:
        - 基础:
            - '原地算法': 'algre/in-place.md'
            - '二分算法': 'algre/part-two.md'
            - '双指针': 'algre/double-pointer.md'
            - '分治算法': 'algre/diverce.md'
            - '数组算法': 'algre/数组算法.md'
            - '排序算法': 'algre/排序算法.md'
            - '字符串算法': 'algre/字符串算法.md'
            - '栈队列算法': 'algre/栈队列算法.md'
            - '链表算法': 'algre/链表算法.md'
            - '树算法': 'algre/树算法.md'
            - '字典树': 'algre/字典树.md'
            - '贪心算法': 'algre/贪心算法.md'
        - 前端算法指南:
            - '01-反转链表': 'algre/01-反转链表.md'
            - '02-环形链表': 'algre/02-环形链表.md'
            - '03-链表合并': 'algre/03-链表合并.md'
            - '04-求链表中间节点': 'algre/04-求链表中间节点.md'
            - '05-二叉树层序遍历': 'algre/05-二叉树层序遍历.md'
            - '06-无权图 BFS 遍历': 'algre/06-无权图 BFS 遍历.md'
            - '07-实现优先队列': 'algre/07-实现优先队列.md'
            - '08-双端队列及应用': 'algre/08-双端队列及应用.md'
            - '09-栈和队列的相互实现': 'algre/09-栈和队列的相互实现.md'
            - '10-n 数之和': 'algre/10-n 数之和.md'
            - '11-二叉树': 'algre/11-二叉树.md'
        - 高级:
            - 'K-means 聚类算法': 'algre/K-means.md'
            - 'LeetCode刷题方法': 'algre/LeetCode刷题方法.md'
            - '刷题窍门': 'algre/刷题窍门.md'
            - '常见算法思想': 'algre/常见算法思想.md'
            - '图算法': 'algre/图算法.md'
    - Javascript:
        - 'ES6-阮一峰': 'javascript/ES6-阮一峰.md'
        - 'ES6 迭代器与生成器': 'javascript/ES6 迭代器与生成器.md'
        - 'ES6newFeature': 'javascript/ES6newFeature.md'
        - 'JS 性能优化': 'javascript/JS 性能优化.md'
        - 'es6': 'javascript/es6.md'
        - '常用到的ES6语法': 'javascript/常用到的ES6语法.md'
    - typescript:
        - '01-简介': 'typescript/01-简介.md'
        - '02-基础': 'typescript/02-基础.md'
        - '03-进阶': 'typescript/03-进阶.md'
        - '04-工程化开发-测试编译': 'typescript/04-工程化开发-测试编译.md'
        - '网易云课堂TS入门': 'typescript/网易云课堂TS入门.md'
        - '01-上手TypeScript': 'typescript/01-上手TypeScript.md'
        - '02-TS-Gulp': 'typescript/02-TS-Gulp.md'
        - '03-JavaScript迁移': 'typescript/03-JavaScript迁移.md'
        - '04-React & Webpack': 'typescript/04-React & Webpack.md'
        - 'TS 常见问题整理': 'typescript/TS 常见问题整理.md'
        - 'TypeScript编译器-downlevelIteration': 'typescript/TypeScript编译器 – 为什么默认情况下不启用downlevelIteration？.md'
        - 'typescript 编译选项和配置文件': 'typescript/typescript 编译选项和配置文件.md'
    - react:
        - 基础:
            - 'React FAQ': 'react/React FAQ.md'
            - 'React PureComponent 使用指南': 'react/React PureComponent 使用指南.md'
            - 'React 的 PureComponent 与 Component': 'react/React 的 PureComponent 与 Component.md'
            - 'React 各种bug 会实时更新': 'react/React 各种bug 会实时更新.md'
            - 'React 操作元素的API': 'react/React 操作元素的API.md'
            - 'React 新生命周期--getDerivedStateFromProps': 'react/React新生命周期--getDerivedStateFromProps.md'
            - 'React 中数据传输': 'react/React中数据传输.md'
            - 'React 生命周期流程图': 'react/React生命周期流程图.md'
            - 'Refs & DOM': 'react/Refs & DOM.md'
            - 'getDerivedStateFromProps的使用': 'react/getDerivedStateFromProps的使用.md'
            - 'react 中通过ref获取高阶（HOC）子组件实例的解决方案': 'react/react 中通过ref获取高阶（HOC）子组件实例的解决方案.md'
            - 'reactjs源码分析-上篇（首次渲染实现原理）': 'react/reactjs源码分析-上篇（首次渲染实现原理）.md'
            - 'reactjs源码分析-下篇（更新机制实现原理）': 'react/reactjs源码分析-下篇（更新机制实现原理）.md'
            - '对 React children理解': 'react/对React children理解.md'
        - 高级:
            - 'React 高阶组件': 'react/React 高阶组件.md'
            - 'React 中的事件处理': 'react/React 中的事件处理.md'
            - 'React-advanced-guides': 'react/React-advanced-guides.md'
            - 'react 项目结构及编码规范': 'react/react 项目结构及编码规范.md'
            - 'React-高阶API': 'react/React-高阶API.md'
        - 性能优化:
            - 'React 强制更新组件': 'react/React 强制更新组件.md'
            - 'React-Design Principles': 'react/React-Design Principles.md'
            - 'React-Hooks': 'react/React-Hooks.md'
            - 'React-Suspense的实现与探讨': 'react/React-Suspense的实现与探讨-没看明白.md'
            - 'React-性能优化': 'react/React-性能优化.md'
            - 'React.Children的API': 'react/React.Children的API.md'
            - 'React.Component': 'react/React.Component.md'
            - 'React.children介绍': 'react/React.children介绍.md'
            - 'React事件': 'react/React事件.md'
            - 'React数据流': 'react/React数据流.md'
            - 'React获取尺寸': 'react/React获取尺寸.md'
    - 工程化:
        - '前端监控理论': 'project/前端监控理论.md'
        - 'React & Webpack': 'project/React & Webpack.md'
        - 'TS-React-Webpack': 'project/TS-React-Webpack.md'
    - 课程笔记:
        - '00-目录': 'netease/00-目录.md'
        - '02-v8引擎回收内存简介': 'netease/02-v8引擎回收内存简介.md'
        - '03-node下面的Restful实现': 'netease/03-node下面的Restful实现.md'
        - '04-编程思想的提升—如何提高我们代码的可扩展性': 'netease/04-编程思想的提升—如何提高我们代码的可扩展性.md'
        - '06-浏览器渲染原理和ssr': 'netease/06-浏览器渲染原理和ssr.md'
        - '07-网易真实项目webpack配置解析': 'netease/07-网易真实项目webpack配置解析.md'
        - '08-从架构分析API层': 'netease/08-从架构分析API层.md'
        - '09-前端负责人的工作内容': 'netease/09-前端负责人的工作内容.md'
        - '10-分析源码学架构': 'netease/10-分析源码学架构.md'
        - '11-设计模式高质量代码': 'netease/11-设计模式高质量代码.md'
        - '12-nodeJS+MongoDB登录系统': 'netease/12-nodeJS+MongoDB登录系统.md'
        - '12-nodejs-mongodb-mongoose': 'netease/12-nodejs-mongodb-mongoose.md'
        - '13-使用VUE创建组件（没学完）': 'netease/13-使用VUE创建组件（没学完）.md'
        - '16-构建自己的脚手架工具': 'netease/16-构建自己的脚手架工具.md'
        - '17-webpack编译原理分析': 'netease/17-webpack编译原理分析.md'
        - '20-组件封装的基本技能-VUE（没学完）': 'netease/20-组件封装的基本技能-VUE（没学完）.md'
        - '21-ssr': 'netease/21-ssr.md'
        - '24-单元测试如何做': 'netease/24-单元测试如何做.md'
        - '25-基于NodeJS打造Web架构中间层': 'netease/25-基于NodeJS打造Web架构中间层.md'
        - '26-webpack的高级技巧': 'netease/26-webpack的高级技巧.md'
    - 重点背诵:
        - '01 面试题1-(1-30)': 'interview/01 面试题1-(1-30).md'
        - '02 面试题1-(30-60)': 'interview/02 面试题1-(30-60).md'
        - '03 面试题1-(60-100)': 'interview/03 面试题1-(60-100).md'
        - '04 面试题2-比较老': 'interview/04 面试题2-比较老.md'
        - '05 面试题5-有答案': 'interview/05 面试题5-有答案.md'
        - '06 大厂要求': 'interview/06 大厂要求.md'
        - '07 面试题1-(101-136)': 'interview/07 面试题1-(101-136).md'
        - '08 面试题3-没答案': 'interview/08 面试题3-没答案.md'
        - '09 面试题4(全栈)': 'interview/09 面试题4(全栈).md'
        - '10 HR面试题目-正在做': 'interview/10 HR面试题目-正在做.md'
        - '11 豪情大佬日常工作感悟': 'interview/11 豪情大佬日常工作感悟.md'
        - '12 知识体系': 'interview/12 知识体系.md'
        - '13 facebook 国外面试': 'interview/13 facebook 国外面试.md'
        - '14 阿里1-4面面经': 'interview/14 阿里1-4面面经.md'
        - '15 JavaScript 基础': 'interview/15 JavaScript 基础.md'
        - '16 面试': 'interview/16 面试.md'
