site_name: Michale An Blog
site_author: Michael An
site_url: https://michael18811380328.github.io/
repo_name: Michael18811380328/Michael18811380328.github.io
repo_url: https://github.com/Michael18811380328/Michael18811380328.github.io
copyright: Copyright &copy; Michael An

docs_dir: ./docs

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - javascript
        - python

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

plugins:
  - search # necessary for search to work

extra:
  search:
    language: 'jp'

extra_javascript:
    - 'js/baidu-statistics.js'

# Page tree
nav:
    - 介绍: 'about/README.md'
    - NodeJS:
        - 基础:
            - '01-Node.js 教程.md': 'nodejs/01-Node.js 教程.md'
            - '02-Node.js 安装配置.md': 'nodejs/02-Node.js 安装配置.md'
            - '03-Node.js 创建第一个应用.md': 'nodejs/03-Node.js 创建第一个应用.md'
            - '05-Node.js REPL(交互式解释器).md': 'nodejs/05-Node.js REPL(交互式解释器).md'
            - '06-Node.js 回调函数.md': 'nodejs/06-Node.js 回调函数.md'
            - '07-Node.js 事件循环.md': 'nodejs/07-Node.js 事件循环.md'
            - '08-Node.js EventEmitter.md': 'nodejs/08-Node.js EventEmitter.md'
            - '09-Node.js Buffer(缓冲区).md': 'nodejs/09-Node.js Buffer(缓冲区).md'
            - '10-Node.js Stream(流).md': 'nodejs/10-Node.js Stream(流).md'
            - '11-Node.js模块系统.md': 'nodejs/11-Node.js模块系统.md'
            - '12-Node.js 函数.md': 'nodejs/12-Node.js 函数.md'
            - '13-Node.js 路由.md': 'nodejs/13-Node.js 路由.md'
            - '14-Node.js 全局对象.md': 'nodejs/14-Node.js 全局对象.md'
            - '15-Node.js 常用工具.md': 'nodejs/15-Node.js 常用工具.md'
            - '16-Node.js 文件系统.md': 'nodejs/16-Node.js 文件系统.md'
            - '17-Node.js GETPOST请求.md': 'nodejs/17-Node.js GETPOST请求.md'
            - '18-Node.js 工具模块.md': 'nodejs/18-Node.js 工具模块.md'
            - '19-Node.js Web 模块.md': 'nodejs/19-Node.js Web 模块.md'
            - '20-Node.js Express 框架.md': 'nodejs/20-Node.js Express 框架.md'
            - '21-Node.js RESTful API.md': 'nodejs/21-Node.js RESTful API.md'
            - '22-Node.js 多进程.md': 'nodejs/22-Node.js 多进程.md'
            - '23-Node.js JXcore 打包.md': 'nodejs/23-Node.js JXcore 打包.md'
            - '24-Node.js 连接 MySQL.md': 'nodejs/24-Node.js 连接 MySQL.md'
            - '25-Node.js 连接 MongoDB.md': 'nodejs/25-Node.js 连接 MongoDB.md'
        - 高级:
            - 'Node 下 LDAP 实现.md': 'nodejs/Node 下 LDAP 实现.md'
            - 'Node.js-fs文档.md': 'nodejs/Node.js-fs文档.md'
            - 'Node.js-path.md': 'nodejs/Node.js-path.md'
            - 'Node.js-全局变量.md': 'nodejs/Node.js-全局变量.md'
            - 'Node.js使用 Nodemailer 发送邮件.md': 'nodejs/Node.js使用Nodemailer发送邮件.md'
            - 'NodeJS.md': 'nodejs/NodeJS.md'
            - 'node-debug.md': 'nodejs/node-debug.md'
            - 'nodeJS 基础教程.md': 'nodejs/nodeJS 基础教程.md'
            - 'nodeJS+mysql+连接池.md': 'nodejs/nodeJS+mysql+连接池.md'
            - 'nodejs api学习：fs.createReadStreame().md': 'nodejs/nodejs api学习：fs.createReadStreame().md'
            - 'node定时器.md': 'nodejs/node定时器.md'
            - '使用nodejs连接mysql数据库实现增删改查.md': 'nodejs/使用nodejs连接mysql数据库实现增删改查.md'
            - '廖雪峰 NodeJS.md': 'nodejs/廖雪峰 NodeJS.md'
            - '命令行的nodeJS.md': 'nodejs/命令行的nodeJS.md'
    - SQL:
        - '阿里云MySQL入门': 'SQL/阿里云MySQL入门.md'
        - '数据库概念': 'SQL/数据库概念.md'
        - '深入MySQL数据库': 'SQL/深入MySQL数据库.md'
        - 'Mac pip install mysql-python unsuccessful': 'SQL/Mac pip install mysql-python unsuccessful.md'
        - 'Mac 安装 MySQLdb（python-mysql）模块': 'SQL/Mac安装MySQLdb（python-mysql）模块.md'
        - 'Python 操作 MySQL数据库': 'SQL/Python操作 MySQL数据库.md'
        - 'SQLite-API-Python': 'SQL/SQLite-API-Python.md'
    - python:
        - 'django-basic': 'python/django-basic.md'
        - 'django': 'python/django.md'
        - 'flask快速开始': 'python/falsk快速开始.md'
        - 'flask 网易云课堂': 'python/flask 网易云课堂.md'
        - '安装pandas时出现环境错误': 'python/安装pandas时出现环境错误.md'
        - '搭建python3开发环境': 'python/搭建python3开发环境.md'
        - 'ValueError Length mismatch Expected axis has 0 elements, new values have 2 elements': 'python/【解决】ValueError Length mismatch Expected axis has 0 elements, new values have 2 elements.md'
        - 'ERROR No matching distribution found for Django==3.0.2 (from -r requirements.txt (line 4))': 'python/ERROR No matching distribution found for Django==3.0.2 (from -r requirements.txt (line 4)).md'
    - About:
        - '关于我': 'about/README.md'
        - '学习日志': 'about/log.md'
