site_name: Michale An Blog
site_author: Michael An
docs_dir: ./docs
copyright: Copyright &copy; TEST

theme: material

plugins:
  - search # necessary for search to work
  - awesome-pages

# Page tree
nav:
    - 介绍: 'about/README.md'
    - 算法:
        - '原地算法': 'algre/in-place.md'
        - '二分算法': 'algre/part-two.md'
        - '双指针': 'algre/double-pointer.md'
        - '分治算法': 'algre/diverce.md'
        - '聚类算法': 'algre/K-means.md'
    - Javascript:
        - 'ES6 迭代器与生成器': 'javascript/ES6 迭代器与生成器.md'
        - 'ES6-阮一峰.md': 'javascript/ES6-阮一峰.md'
        - 'ES6newFeature.md': 'javascript/ES6newFeature.md'
        - 'JS 性能优化.md': 'javascript/JS 性能优化.md'
        - 'es6.md': 'javascript/es6.md'
        - '常用到的ES6语法.md': 'javascript/常用到的ES6语法.md'
    - SQL:
        - 'Mac pip install mysql-python unsuccessful': 'SQL/Mac pip install mysql-python unsuccessful.md'
        - 'Mac安装MySQLdb（python-mysql）模块': 'SQL/Mac安装MySQLdb（python-mysql）模块.md'
        - 'Python操作 MySQL数据库': 'SQL/Python操作 MySQL数据库.md'
        - 'SQLite-API-Python': 'SQL/SQLite-API-Python.md'
        - '深入MySQL数据库': 'SQL/深入MySQL数据库.md'
        - '阿里云MySQL入门': 'SQL/阿里云MySQL入门.md'
        - '数据库概念': 'SQL/数据库概念.md'
    - python:
        - 'ERROR No matching distribution found for Django==3.0.2 (from -r requirements.txt (line 4)).md': 'python/ERROR No matching distribution found for Django==3.0.2 (from -r requirements.txt (line 4)).md'
        - 'django-basic.md': 'python/django-basic.md'
        - 'django.md': 'python/django.md'
        - 'flask快速开始.md': 'python/falsk快速开始.md'
        - 'flask 网易云课堂.md': 'python/flask 网易云课堂.md'
        - '安装pandas时出现环境错误.md': 'python/安装pandas时出现环境错误.md'
        - '搭建python3开发环境.md': 'python/搭建python3开发环境.md'
        - 'ValueError Length mismatch Expected axis has 0 elements, new values have 2 elements.md': 'python/【解决】ValueError Length mismatch Expected axis has 0 elements, new values have 2 elements.md'
    - typescript:
        - '01-简介.md': 'typescript/01-简介.md'
        - '02-基础.md': 'typescript/02-基础.md'
        - '03-进阶.md': 'typescript/03-进阶.md'
        - '04-工程化开发-测试编译.md': 'typescript/04-工程化开发-测试编译.md'
        - '网易云课堂TS入门.md': 'typescript/网易云课堂TS入门.md'
    - react:
        - basic:
            - 'React FAQ.md': 'react/React FAQ.md'
            - 'React PureComponent 使用指南.md': 'react/React PureComponent 使用指南.md'
            - 'React 的 PureComponent 与 Component.md': 'react/React 的 PureComponent 与 Component.md'
            - 'React 各种bug 会实时更新.md': 'react/React 各种bug 会实时更新.md'
            - 'React 操作元素的API.md': 'react/React 操作元素的API.md'
            - 'React新生命周期--getDerivedStateFromProps.md': 'react/React新生命周期--getDerivedStateFromProps.md'
            - 'React中数据传输.md': 'react/React中数据传输.md'
            - 'React生命周期流程图.md': 'react/React生命周期流程图.md'
            - 'Refs & DOM.md': 'react/Refs & DOM.md'
            - 'getDerivedStateFromProps的使用.md': 'react/getDerivedStateFromProps的使用.md'
            - 'react 中通过ref获取高阶（HOC）子组件实例的解决方案.md': 'react/react 中通过ref获取高阶（HOC）子组件实例的解决方案.md'
            - 'reactjs源码分析-上篇（首次渲染实现原理）.md': 'react/reactjs源码分析-上篇（首次渲染实现原理）.md'
            - 'reactjs源码分析-下篇（更新机制实现原理）.md': 'react/reactjs源码分析-下篇（更新机制实现原理）.md'
            - '对React children理解.md': 'react/对React children理解.md'
        - advance:
            - 'React 高阶组件.md': 'react/React 高阶组件.md'
            - 'React 中的事件处理.md': 'react/React 中的事件处理.md'
            - 'React-advanced-guides.md': 'react/React-advanced-guides.md'
            - 'react 项目结构及编码规范.md': 'react/react 项目结构及编码规范.md'
            - 'React-高阶API.md': 'react/React-高阶API.md'
        - 性能优化:
            - 'React 强制更新组件.md': 'react/React 强制更新组件.md'
            - 'React-Design Principles.md': 'react/React-Design Principles.md'
            - 'React-Hooks.md': 'react/React-Hooks.md'
            - 'React-Suspense的实现与探讨-没看明白.md': 'react/React-Suspense的实现与探讨-没看明白.md'
            - 'React-性能优化.md': 'react/React-性能优化.md'
            - 'React.Children的API.md': 'react/React.Children的API.md'
            - 'React.Component.md': 'react/React.Component.md'
            - 'React.children介绍.md': 'react/React.children介绍.md'
            - 'React事件.md': 'react/React事件.md'
            - 'React数据流.md': 'react/React数据流.md'
            - 'React获取尺寸.md': 'react/React获取尺寸.md'
            - '': ''
    - About:
        - '关于我': 'about/README.md'
