# yaml 配置
version: "3"

# 该 Compose 文件定义了两个服务：web 和 redis
services:
  # web：Flask 服务使用从 Dockerfile 当前目录中构建的镜像。它将容器和主机绑定到暴露的端口 5000。使用 Flask Web 服务器的默认端口 5000。
  web:
    build: .
    container_name: michael-web
    ports:
      - 5000:5000

  # 注意，第一个web服务和第二个 web 服务会冲突，第一个启动默认网络镜像，运行 flask，第二个运行 apache 镜像（个人新增）
  # web：web 服务使用使用 apache 服务器镜像，端口映射是 8080，设置卷位置（文件位置）是 web 目录
  # web:
  #   container_name: michael-apache2
  #   image: httpd
  #   ports:
  #       - "8080:80"
  #   privileged: true
  #   volumes:
  #       - "./web/:/usr/local/apache2/htdocs/"

  # 该 redis 服务使用 Docker Hub 的公共 Redis 映像
  redis:
    image: "redis:alpine"
    container_name: michael-redis
    ports:
      - 6379:6379
