site_name: Michale An Blog
site_author: Michael An
site_url: https://michael18811380328.github.io/
repo_name: Michael18811380328/Michael18811380328.github.io
repo_url: https://github.com/Michael18811380328/Michael18811380328.github.io
copyright: Copyright &copy; Michael An

docs_dir: ./docs

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - javascript
        - python
    palette:
        # primary: "red"
        # primary: "deep orange"
        primary: "orange"
        # primary: "blue"
        # primary: "pirple"
        # primary: "green"

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

plugins:
  - search # necessary for search to work

extra:
  search:
    language: 'jp'

extra_javascript:
    - 'js/baidu-statistics.js'

# Page tree
nav:
    - About:        
        - '说明': 'index.md'
        - 'README.md': 'README.md'
        - '学习日志': 'log.md'
    - ruby:
        - 'Github+Jekyll.md': 'ruby/Github+Jekyll.md'
        - 'install-ruby.md': 'ruby/install-ruby.md'
        - 'jekyll-basic.md': 'ruby/jekyll-basic.md'
        - 'jekyll-install.md': 'ruby/jekyll-install.md'
        - 'ruby-readme.md': 'ruby/ruby-readme.md'
    - 其他日志存档:
        - 'algorithm-sort.md': 'old/algorithm-sort.md'
        - 'alibaba-open-source-instructions.md': 'old/alibaba-open-source-instructions.md'
        - 'browser-sync.md': 'old/browser-sync.md'
        - 'ice-instructions.md': 'old/ice-instructions.md'
        - 'localstorage.md': 'old/localstorage.md'
        - 'mui-instructions.md': 'old/mui-instructions.md'
        - 'my-profession-life.md': 'old/my-profession-life.md'
        - 'personal_experience.md': 'old/personal_experience.md'
        - 'pro_city_district.md': 'old/pro_city_district.md'
        - 'showdoc_saying.md': 'old/showdoc_saying.md'
        - 'tool-instructions.md': 'old/tool-instructions.md'
        - 'typescript.md': 'old/typescript.md'
        - 'vue_responsive_principle.md': 'old/vue_responsive_principle.md'
        - 'vue_websocket.md': 'old/vue_websocket.md'
