site_name: Michale An Blog
site_author: Michael An
site_url: https://michael18811380328.github.io/
repo_name: Michael18811380328/Michael18811380328.github.io
repo_url: https://github.com/Michael18811380328/Michael18811380328.github.io
copyright: Copyright &copy; Michael An

docs_dir: ./docs

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - javascript
        - python
    palette:
        # primary: "red"
        # primary: "deep orange"
        primary: "orange"
        # primary: "blue"
        # primary: "pirple"
        # primary: "green"

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

plugins:
  - search # necessary for search to work

extra:
  search:
    language: 'jp'

extra_javascript:
    - 'js/baidu-statistics.js'

# Page tree
nav:
    - About:
        - '说明': 'index.md'
        - '学习日志': 'log.md'
        - '临时日志': '临时.md'
    - 早期日志存档:
        - 'BUG-Auto packing the repository in background for optimum performance': 'old/BUG-Auto packing the repository in background for optimum performance.md'
        - 'JS-testing': 'old/JS-testing.md'
        - 'JSzip': 'old/JSzip.md'
        - 'React-Router': 'old/React-Router.md'
        - 'Translation': 'old/Translation.md'
        - 'docker-basic-use': 'old/docker-basic-use.md'
        - 'editor-js': 'old/editor-js.md'
        - 'install-ruby': 'old/install-ruby.md'
        - 'jekyll-install': 'old/jekyll-install.md'
        - 'markdown-new-style': 'old/markdown-new-style.md'
        - 'react-responsive': 'old/react-responsive.md'
        - 'text-runner': 'old/text-runner.md'
        - 'welcome-to-jekyll': 'old/welcome-to-jekyll.md'
        - 'Ruby': 'ruby/readme.md'

