site_name: Michale An Blog
site_author: Michael An
site_url: https://michael18811380328.github.io/
repo_name: Michael18811380328/Michael18811380328.github.io
repo_url: https://github.com/Michael18811380328/Michael18811380328.github.io
copyright: Copyright &copy; Michael An

docs_dir: ./docs

theme:
    name: material
    highlightjs: true
    hljs_languages:
        - yaml
        - bash
        - javascript
        - python
    palette:
        # primary: "red"
        # primary: "deep orange"
        primary: "orange"
        # primary: "blue"
        # primary: "pirple"
        # primary: "green"

extra_javascript:
    - 'js/baidu-statistics.js'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

plugins:
  - search # necessary for search to work

extra:
  search:
    language: 'jp'

# Page tree
nav:
    - About:        
        - '说明': 'index.md'
        - '学习日志': 'log.md'
    - ruby:
        - 'install-ruby.md': 'ruby/install-ruby.md'
        - 'jekyll-basic.md': 'ruby/jekyll-basic.md'
        - 'jekyll-install.md': 'ruby/jekyll-install.md'
        - 'ruby-readme.md': 'ruby/ruby-readme.md'
    - 其他日志存档:
        - '2018-09-11-browser-sync.markdown': 'old/2018-09-11-browser-sync.markdown'
        - '2018-09-11-ice-instructions.markdown': 'old/2018-09-11-ice-instructions.markdown'
        - '2018-09-12-algorithm.markdown': 'old/2018-09-12-algorithm.markdown'
        - '2018-09-12-localstorage.markdown': 'old/2018-09-12-localstorage.markdown'
        - '2018-09-26-pro_city_district.markdown': 'old/2018-09-26-pro_city_district.markdown'
        - '2018-10-11-typescript.markdown': 'old/2018-10-11-typescript.markdown'
        - '2018-10-14-vue_websocket.markdown': 'old/2018-10-14-vue_websocket.markdown'
        - '2018-10-16-showdoc_saying.markdown': 'old/2018-10-16-showdoc_saying.markdown'
        - '2018-10-18-personal_experience.markdown': 'old/2018-10-18-personal_experience.markdown'
        - '2018-10-18-vue_responsive_principle.markdown': 'old/2018-10-18-vue_responsive_principle.markdown'
        - '2018-11-18-mui-instructions.markdown': 'old/2018-11-18-mui-instructions.markdown'
        - '2018-11-20-tool-instructions.markdown': 'old/2018-11-20-tool-instructions.markdown'
        - '2018-11-29-uni-app-instructions.markdown': 'old/2018-11-29-uni-app-instructions.markdown'
        - '2018-12-01-git-introduce.markdown': 'old/2018-12-01-git-introduce.markdown'
        - '2018-12-02-my-profession-life.markdown': 'old/2018-12-02-my-profession-life.markdown'
        - '2018-12-14-alibaba-open-source-instructions.markdown': 'old/2018-12-14-alibaba-open-source-instructions.markdown'
        - 'algorithm-sort.md': 'old/algorithm-sort.md'
        - 'alibaba-open-source-instructions.md': 'old/alibaba-open-source-instructions.md'
        - 'browser-sync.md': 'old/browser-sync.md'
        - 'ice-instructions.md': 'old/ice-instructions.md'
        - 'localstorage.md': 'old/localstorage.md'
        - 'mui-instructions.md': 'old/mui-instructions.md'
        - 'my-profession-life.md': 'old/my-profession-life.md'
        - 'personal_experience.md': 'old/personal_experience.md'
        - 'pro_city_district.md': 'old/pro_city_district.md'
        - 'showdoc_saying.md': 'old/showdoc_saying.md'
        - 'tool-instructions.md': 'old/tool-instructions.md'
        - 'typescript.md': 'old/typescript.md'
        - 'vue_responsive_principle.md': 'old/vue_responsive_principle.md'
        - 'vue_websocket.md': 'old/vue_websocket.md'
