# coding=utf-8

try:
    fh = open('test.md', 'w')
    fh.write("This is Michael An test file generated by python")
except IOError:
    print('Error: file not found or read file error')
else:
    print('write content in this file successfilly')
    fh.close()

# finilly we find a new file 'testfile' in this dir
