site_name: Michale An Blog
site_author: Michael An
site_url: https://michael18811380328.github.io/
repo_name: Michael18811380328/Michael18811380328.github.io
repo_url: https://github.com/Michael18811380328/Michael18811380328.github.io
copyright: Copyright &copy; Michael An

docs_dir: ./docs

theme:
    name: material
    palette:
        primary: "blue"

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta

plugins:
  - search # necessary for search to work

extra_javascript:
    - 'js/baidu-statistics.js'

extra:
  search:
    language: 'jp'

# Page tree
nav:
    - 人生思考:
        - '40退休.md': '40退休.md'
        - 'Poor-and-busy.md': 'Poor-and-busy.md'
        - 'Reflections on Pre-Tirement.md': 'Reflections on Pre-Tirement.md'
        - 'The art of Execution 执行力的艺术.md': 'The art of Execution 执行力的艺术.md'
        - 'b计划.md': 'b计划.md'
        - '熵增.md': '熵增.md'
        - '个人选择.md': '个人选择.md'
        - '人生真相.md': '人生真相.md'
        - '丹尼斯与Unix.md': '丹尼斯与Unix.md'
        - '詹宏志读书.md': '詹宏志读书.md'
        - '骡子和人生.md': '骡子和人生.md'
        - '如何变得强大.md': '如何变得强大.md'
        - '专业教育的兴起.md': '专业教育的兴起.md'
        - '中国经济的转变.md': '中国经济的转变.md'
        - '硕士学位的贬值.md': '硕士学位的贬值.md'
        - '任正非的管理思想.md': '任正非的管理思想.md'
        - '技术和稳定的工作.md': '技术和稳定的工作.md'
        - '大学教育和网络文凭.md': '大学教育和网络文凭.md'
        - '思维导图到深度学习.md': '思维导图到深度学习.md'
        - '工业文明对于社会的冲击.md': '工业文明对于社会的冲击.md'
        - '正态分布和对数正态分布.md': '正态分布和对数正态分布.md'
